access_key_id: YOUR_ACCESS_KEY_ID
secret_access_key: YOUR_SECRET_ACCESS_KEY
receive_queue_name: Test_queue

# Queue type: raw, s3, url
receive_queue_type: raw

# (true/false)
store_message: false

# (true/false)
decompress_message: false

# Available vars: $input_file, $id, $full_msg_file
process_command: "cat $input_file"

# (true/false)
retry_on_failure: false

retries: 0

polling_options:
  :wait_time_seconds: 20

# none, post_to_results_queue
result_step: none

result_queue_name: ""

# Queue type: raw, s3
result_queue_type: raw

result_s3_bucket: ""

# (true/false)
compress_result: false

# (true/false)
keep_trail: false

# Available vars: $input_file, $id, $full_msg_file
cleanup_command: ""

# (true/false)
halt_instance_on_timeout: false

# 0 to turn off
smart_halt_when_idle_N_seconds: 0

# stop, terminate
halt_type: terminate
