# How to use this config file, in 3 easy steps:
# 1. To add a new launch TYPE, add an entry with a new name under the ami_map
#    section. Reference the appropriate AMI. The TYPE is really just a label
#    for associating a group of settings. You can have two TYPEs that are
#    exactly the same except for one minor detail in the userdata (for example).
# 2. Fill out any required overrides for a launch type in the security,
#    launch_settings, and userdata sections. Use the same type name as in step
#    one if you're setting up a new type.
# 3. There are really only two steps.

# Map type labels to specific AMIs. New types can be added by adding a
# new label and AMI in this section

# 'ami-4ab61122' is 30gb windows base
# 'ami-baf652d2' IN 4 proc ssd
# 'ami-34f3575c' IN 4 proc mag
# 'ami-a8ff5bc0' IN 1 proc ssd
# 'ami-30f85c58' IN 1 proc mag
# 'ami-7a822612' IN 4 proc ssd long timeout

ami_map:
  # Windows
  worker:         'ami-4ab61122'
  worker_Purdue:  'ami-4ab61122'
  #worker_ISA:     'ami-4ab61122'
  worker_ISA:     'ami-4ab61122'
  worker_r2_ISA:  'ami-4ab61122'
  worker_ISU:     'ami-4ab61122'
  server_worker_ISU:  'ami-4ab61122'   #'ami-7e32e816' #<--ssd_r2 'ami-c85f85a0' # <-- magnetic
  server_worker_IN: 'ami-7a822612' #'ami-4ab61122'
  worker_mmp_dev: 'ami-4ab61122'
  worker_mmp_staging: 'ami-4ab61122'
  worker_mmp_prod:    'ami-4ab61122'
  pregrid:        'ami-4ab61122'
  pregrid_Purdue: 'ami-4ab61122'
  pregrid_ISA:    'ami-4ab61122'
  pregrid_ISU:    'ami-4ab61122'
  pregrid_IN:     'ami-4ab61122'
  # Linux
  reporthandler:  'ami-f4419c9c'
  aggregator:     'ami-f4419c9c'
  aggregator_r2:  'ami-f4419c9c'
  errorhandler:   'ami-f4419c9c'


# Security-related settings for instances. The settings in 'base' will be merged
# with any settings specified on a per-type basis, with the per-type settings
# taking precedence. All available options appear in the base section.
security:
  base:
    vpc_id: 'vpc-e894b787'
    vpc_subnet: 'subnet-fc94b793' # development-private
    #vpc_subnet: 'subnet-0f9ebd60' # staging-private
    #vpc_subnet: 'subnet-b2f1ff9a' # spot-1  4proc ssd
    #vpc_subnet: 'subnet-83f1ffab' # spot-2  4proc ssd
    #vpc_subnet: 'subnet-9bf1ffb3' # spot-3  4proc ssd
    #vpc_subnet: 'subnet-92f1ffba' # spot-4  4proc ssd
    #vpc_subnet: 'subnet-f1d7dfd9' # spot-5
    #vpc_subnet: 'subnet-c7d7dfef' # spot-6
    #vpc_subnet: 'subnet-d6d7dffe' # spot-7
    #vpc_subnet: 'subnet-3be8e013' # spot-8
    #vpc_subnet: 'subnet-1ee8e036' # spot-9
    #vpc_subnet: 'subnet-6be8e043' # spot-10
    #vpc_subnet: 'subnet-63e8e04b' # spot-11
    #vpc_subnet: 'subnet-72e8e05a' # spot-12
    #vpc_subnet: 'subnet-54e8e07c' # spot-13
    #vpc_subnet: 'subnet-a1e8e089' # spot-14
    #vpc_subnet: 'subnet-b7e8e09f' # spot-15
    #vpc_subnet: 'subnet-81e8e0a9' # spot-16
    #vpc_subnet: 'subnet-ece8e0c4' # spot-17
    #vpc_subnet: 'subnet-fae8e0d2' # spot-18
    #vpc_subnet: 'subnet-f2e8e0da' # spot-19
    #vpc_subnet: 'subnet-dce8e0f4' # spot-20
    
    
    # If you override this on a per-type basis, be aware that the *values* in
    # the array will not be merged. You must override the entire array.
    security_groups: ['dev-base','dev-kibitz-worker']

  errorhandler:
    security_groups: ['dev-base','dev-kibitz-worker','dev-dashboard']

  worker_mmp_dev:
    vpc_id: 'vpc-e894b787'
    vpc_subnet: 'subnet-fc94b793'
    # If you override this on a per-type basis, be aware that the *values* in
    # the array will not be merged. You must override the entire array.
    security_groups: ['dev-base','dev-kibitz-worker']

  worker_mmp_staging:
    vpc_id: 'vpc-e894b787'
    vpc_subnet: 'subnet-fc94b793'
    # If you override this on a per-type basis, be aware that the *values* in
    # the array will not be merged. You must override the entire array.
    security_groups: ['dev-base','dev-kibitz-worker']

  worker_mmp_prod:
    vpc_id: 'vpc-e894b787'
    vpc_subnet: 'subnet-cb9ebda4'
    # If you override this on a per-type basis, be aware that the *values* in
    # the array will not be merged. You must override the entire array.
    security_groups: ['production-worker']

# The base settings get merged with any per-type settings. All available options
# appear in the base section.
launch_settings:
  base:
    size: 't1.micro'
    count: 1
    
  #worker:
  #  size: 'c3.8xlarge'
  pregrid:
    size: 't2.medium'
  
  pregrid_ISA:
    size: 't2.medium'
  
  pregrid_Purdue:
    size: 't2.medium'

  pregrid_ISU:
    size: 't2.medium'
    
  pregrid_IN:
    size: 'm3.medium'
    
  worker_Purdue: 
    size: 'c3.8xlarge'

  worker_ISA:
    size: 'm1.medium' #'m3.2xlarge'

  worker_r2_ISA:
    size: 'r3.4xlarge'

  worker_ISU:
    size: 'm1.medium'
    
  server_worker_ISU:
    size: 'm1.medium'
    
  server_worker_IN:
    size: 'm1.xlarge'

  worker_mmp_dev:
    size: 't2.medium'

  worker_mmp_staging:
    size: 't2.medium'

  worker_mmp_prod:
    size: 't2.medium'
    
  aggregator_r2:
    size: 'm3.2xlarge'
    
  aggregator:
    size: 'm3.medium'
    
  reporthandler:
    size: 'm3.medium'

# The information in this section is used to populate the userdata on
# an instance prior to launch. The base section is merged with all launch types.
# Since the userdata is very flexible, NOT ALL POSSIBLE SETTINGS APPEAR IN THE
# BASE SECTION. Any boolean, numeric, or string value can be specified in
# the per-type userdata sections.
userdata:
  base:
    deploy_bucket: 6k_test.praxik
    # The gdb file to use
    gdb_bucket: 6k_test.praxik
    man_bucket: 6k_test.praxik
    r2_man_bucket: 6k_test.praxik
    
    
  worker:
    deploy_key: arks/default/worker_x64.zip
    
  worker_ISA:
    deploy_key: arks/default/worker_x64.zip
    number_of_processes: 1 
    gdb_key: iowammp.gdb.zip
    gdb_install_name: iowammp.gdb
    man_key: ISA_weps.zip
    r2_man_key: ISA_skels.zip
    receive_queue_name: 6k_task

  worker_r2_ISA:
    deploy_key: arks/default/worker_r2p2d_x64.zip
    number_of_processes: 4 
    gdb_key: iowammp.gdb.zip
    gdb_install_name: iowammp.gdb
    man_key: ISA_weps.zip
    r2_man_key: ISA_skels.zip
    receive_queue_name: 6k_task_r2

  worker_ISU:
    deploy_key: arks/default/worker_x64.zip
    number_of_processes: 1 
    gdb_key: iowammp.gdb.zip
    gdb_install_name: iowammp.gdb
    man_key: INL_Webster_weps.zip #PT_York_weps.zip #INL_Marcus_Rev2_weps.zip  #ISU_Marcus_weps.zip
    r2_man_key: INL_Webster_skels.zip #PT_York_skels.zip #INL_Marcus_Rev2_skels.zip   #ISU_Marcus_skels.zip
    receive_queue_name: purdue_task
    
  server_worker_ISU:
    deploy_key: arks/default/server_worker_x64.zip
    number_of_processes: 1 
    gdb_key: iowammp.gdb.zip
    gdb_install_name: iowammp.gdb
    man_key: INL_Webster_weps.zip #PT_York_weps.zip #INL_Marcus_Rev2_weps.zip  #ISU_Marcus_weps.zip
    r2_man_key: INL_Webster_skels.zip #PT_York_skels.zip #INL_Marcus_Rev2_skels.zip   #ISU_Marcus_skels.zip
    receive_queue_name: purdue_task
    keep_alive_check_interval: 30
    server_worker_command: "6k_server_worker.exe --gdbname iowammp.gdb --workerid $pid"
    
    
  server_worker_IN:
    deploy_key: arks/default/server_worker_x64.zip
    number_of_processes: 4 
    gdb_key: iowammp.gdb.zip
    gdb_install_name: iowammp.gdb
    man_key: IN_state_weps.zip
    r2_man_key: IN_state_skels.zip
    receive_queue_name: IN_task
    keep_alive_check_interval: 30
    server_worker_command: "6k_server_worker.exe --gdbname tyner.gdb --workerid $pid"
    
  worker_Purdue:
    deploy_key: arks/purdue/worker_x64.zip
    number_of_processes: 44 
    gdb_key: tyner.gdb.zip
    gdb_install_name: tyner.gdb
    man_key: WEPS_Purdue.zip
    r2_man_key: R2_Purdue.zip
    receive_queue_name: purdue_task

  worker_mmp_dev:
    deploy_key: arks/default/iowammp.zip
    number_of_processes: 2
    db_ip: web-development-mmp360-persistence.csr7bxits1yb.us-east-1.rds.amazonaws.com
    db_port: 5432
    db_user_name: iowammp
    db_password: 1234
    db_name: iowammp_web_development_reports
    geoserver_ip: 10.1.2.8
    geoserver_port: 5432
    s3_bucket: web_development

  worker_mmp_staging:
    deploy_key: arks/default/iowammp.zip
    number_of_processes: 2
    db_ip: web-development-mmp360-persistence.csr7bxits1yb.us-east-1.rds.amazonaws.com
    db_port: 5432
    db_user_name: iowammp
    db_password: 1234
    db_name: iowammp_web_development_reports
    geoserver_ip: 10.1.2.8
    geoserver_port: 5432
    s3_bucket: staging

  worker_mmp_prod:
    deploy_key: arks/default/iowammp_prod.zip
    number_of_processes: 2
    db_ip: persistence.production.mmp360.com
    db_port: 5432
    db_user_name: iowammp
    db_password: dan4yees7d
    db_name: iowammp_production_reports
    geoserver_ip: 10.1.6.8
    geoserver_port: 5432
    s3_bucket: production

  pregrid:
    deploy_key: arks/default/pregrid_x64.zip
 
  pregrid_ISA:
    deploy_key: arks/default/pregrid_x64.zip
    gdb_key: iowammp.gdb.zip
    gdb_install_name: iowammp.gdb
    man_key: ISA_weps.zip
    r2_man_key: ISA_skels.zip
    receive_queue_name: 6k_job

  pregrid_ISU:
    deploy_key: arks/default/pregrid_x64.zip
    gdb_key: iowammp.gdb.zip
    gdb_install_name: iowammp.gdb
    man_key: INL_Webster_weps.zip #PT_York_weps.zip #INL_Marcus_Rev2_weps.zip  #ISU_Marcus_weps.zip
    r2_man_key: INL_Webster_skels.zip #PT_York_skels.zip #INL_Marcus_Rev2_skels.zip   #ISU_Marcus_skels.zip
    receive_queue_name: purdue_job
    
    
  pregrid_IN:
    deploy_key: arks/default/pregrid_x64_IN.zip
    gdb_key: iowammp.gdb.zip
    gdb_install_name: iowammp.gdb
    man_key: IN_state_weps.zip
    r2_man_key: IN_state_skels.zip
    receive_queue_name: IN_job

  pregrid_Purdue:
    deploy_key: arks/purdue/pregrid_x64.zip
    gdb_key: tyner.gdb.zip
    gdb_install_name: tyner.gdb
    man_key: WEPS_Purdue.zip
    r2_man_key: R2_Purdue.zip
    receive_queue_name: purdue_job

  reporthandler:
    deploy_key: arks/default/reporthandler.zip
    receive_queue_name: 6k_report_gen

  aggregator_r2:
    deploy_key: arks/default/aggregator_r2.zip
    receive_queue_name: 6k_aggregator_r2
   
  aggregator:
    deploy_key: arks/default/aggregator.zip
    receive_queue_name: 6k_aggregator

  errorhandler:
    deploy_key: arks/default/errorhandler.zip
