# How to use this config file, in 3 easy steps:
# 1. To add a new launch TYPE, add an entry with a new name under the ami_map
#    section. Reference the appropriate AMI. The TYPE is really just a label
#    for associating a group of settings. You can have two TYPEs that are
#    exactly the same except for one minor detail in the userdata (for example).
# 2. Fill out any required overrides for a launch type in the security,
#    launch_settings, and userdata sections. Use the same type name as in step
#    one if you're setting up a new type.
# 3. There are really only two steps.

# Map type labels to specific AMIs. New types can be added by adding a
# new label and AMI in this section
ami_map:
  worker:        'ami-a39a86ca'
  pregrid:       'ami-a39a86ca'
  reporthandler: 'ami-1352417a'
  #errorhandler:  'ami-1352417a'


# Security-related settings for instances. The settings in 'base' will be merged
# with any settings specified on a per-type basis, with the per-type settings
# taking precedence. All available options appear in the base section.
security:
  base:
    vpc_id: 'vpc-e894b787'
    vpc_subnet: 'subnet-fc94b793'
    # If you override this on a per-type basis, be aware that the *values* in
    # the array will not be merged. You must override the entire array.
    security_groups: ['dev-base','dev-kibitz-worker']


# The base settings get merged with any per-type settings. All available options
# appear in the base section.
launch_settings:
  base:
    size: 't1.micro'
    count: 1
    
  #worker:
  #  size: 'c3.8xlarge'


# The information in this section is used to populate the userdata on
# an instance prior to launch. The base section is merged with all launch types.
# Since the userdata is very flexible, NOT ALL POSSIBLE SETTINGS APPEAR IN THE
# BASE SECTION. Any boolean, numeric, or string value can be specified in
# the per-type userdata sections.
userdata:
  base:
    deploy_bucket: 6k_test.praxik
    # The gdb file to use
    gdb_bucket: 6k_test.praxik
    gdb_key: inl.gdb.zip
    gdb_install_name: inl.gdb
    
  worker:
    deploy_key: arks/default/worker.zip
    number_of_processes: 1

  pregrid:
    deploy_key: arks/default/pregrid.zip

  reporthandler:
    deploy_key: arks/default/reporthandler.zip

  #errorhandler:
  #  deploy_key: arks/default/errorhandler.zip
  
