receive_queue_name: ""

# (true/false)
store_message: false

# (true/false)
decompress_message: false

dont_hit_disk: true

# Available vars: $input_file, $id, $full_msg_file, 
#                 $s3_1, $s3_2, etc. 
#                 $uri_1, $uri_2, etc.
process_command: "ruby rusle2_aggregator.rb $msg_contents"

# (true/false)
retry_on_failure: false

retries: 0

# the idle_timeout option below tells reporthandler (run_r2_polling) to
# timeout after 10 minutes of not receiving results. This timeout only kicks
# in *after* pregrid has put a report_gen task in the report_gen queue.
# We really expect that we shouldn't have to wait more than 10
# minutes between result sets for this job.
polling_options:
  :wait_time_seconds: 20
  :idle_timeout: 600
  :attributes:
    - :all

# none, post_to_result_queue
result_step: none

result_queue_name: ""

# (true/false)
compress_result_message: false

# (true/false)
keep_trail: false

# Available vars: see process_command
cleanup_command: ""

# (true/false)
halt_instance_on_timeout: false

# 0 to turn off
smart_halt_when_idle_N_seconds: 0

# stop, terminate
halt_type: terminate
