receive_queue_name: "mmp_task"

error_queue_name: "mmp_error"

# (true/false)
store_message: false

# (true/false)
decompress_message: false

# Available vars: $input_file, $id, $full_msg_file, 
#                 $s3_1, $s3_2, etc. 
#                 $uri_1, $uri_2, etc.
process_command: "ruby mmp_shim.rb $input_file $pid output_$id.txt"

# (true/false)
retry_on_failure: false

retries: 0

polling_options:
  :wait_time_seconds: 20
  :attributes:
    - :all

# none, post_to_result_queue
result_step: post_to_result_queue

result_queue_name: "mmp_results"

# (true/false)
compress_result_message: false

# (true/false)
keep_trail: false

# Available vars: see process_command
cleanup_command: ""

# Available vars: see process_command
collect_errors_command: ""

# (true/false)
halt_instance_on_timeout: false

# 0 to turn off
smart_halt_when_idle_N_seconds: 0

# stop, terminate
halt_type: terminate
